In [3]:
import numpy as np
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('First matrix is : \n',mat1)
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Second matrix is : \n',mat2)

mat3 = mat1+mat2

print('The Addition of two matrices are : \n mat1+mat2 : \n',mat3)

First matrix is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second matrix is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The additon of two matrices are : 
 mat1+mat2 : 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
